import { describe, expect, test } from "bun:test"
import {
  applyContentForDisk,
  detectArtifactFormat,
  draftFilename,
  extractHtmlBlock,
  extractFirstHeading,
  findLatestAssistantMarkdown,
  wrapHtmlForDisk,
} from "./work-artifact-extract"

const message = (over: Partial<{ id: string; mode: string }> = {}) => ({
  id: over.id ?? "msg_1",
  sessionID: "ses_1",
  role: "assistant" as const,
  time: { created: 1000 },
  parentID: "msg_0",
  modelID: "m",
  providerID: "p",
  mode: over.mode ?? "work",
  agent: "work-orchestrator",
  path: { cwd: "/project", root: "/project" },
  cost: 0,
  tokens: { input: 0, output: 0, reasoning: 0, cache: { read: 0, write: 0 } },
})

const textPart = (text: string) => ({ type: "text" as const, text })

describe("findLatestAssistantMarkdown", () => {
  test("returns the joined text of the latest assistant message", () => {
    const messages = [message({ id: "msg_1" }), message({ id: "msg_2" })]
    const parts = {
      msg_1: [textPart("旧内容")],
      msg_2: [textPart("# 分镜脚本"), textPart("\n\n第二段")],
    }
    expect(findLatestAssistantMarkdown(messages, parts)).toBe("# 分镜脚本\n\n第二段")
  })

  test("returns null when there is no assistant message with text", () => {
    const messages = [message({ id: "msg_1" })]
    const parts = { msg_1: [{ type: "tool" as const, id: "t", name: "question", state: { status: "completed" } }] }
    expect(findLatestAssistantMarkdown(messages, parts)).toBeNull()
  })
})

describe("extractFirstHeading", () => {
  test("extracts the first # heading", () => {
    expect(extractFirstHeading("# 视频分镜脚本\n\n正文")).toBe("视频分镜脚本")
  })

  test("returns null without a heading", () => {
    expect(extractFirstHeading("纯文本正文")).toBeNull()
  })
})

describe("detectArtifactFormat (M3.5)", () => {
  test("detects html when the candidate contains a ```html fenced block", () => {
    expect(detectArtifactFormat('# 拓扑图\n\n```html\n<div id="topo"></div>\n```')).toBe("html")
  })

  test("detects html at the very start of the candidate", () => {
    expect(detectArtifactFormat("```html\n<div></div>\n```")).toBe("html")
  })

  test("detects markdown for plain documents", () => {
    expect(detectArtifactFormat("# PRD\n\n## 背景\n\n正文")).toBe("markdown")
  })

  test("detects markdown for candidates with other fenced blocks", () => {
    expect(detectArtifactFormat("# 文档\n\n```ts\nconst x = 1\n```")).toBe("markdown")
  })
})

describe("extractHtmlBlock (M3.5)", () => {
  test("extracts the first ```html fenced block content", () => {
    const candidate = '# 拓扑图\n\n```html\n<div id="topo"></div>\n<script>new vis.Network();</script>\n```\n\n说明'
    expect(extractHtmlBlock(candidate)).toBe('<div id="topo"></div>\n<script>new vis.Network();</script>')
  })

  test("returns null when there is no html block", () => {
    expect(extractHtmlBlock("# PRD\n\n正文")).toBeNull()
  })

  test('is compatible with an unclosed <artifact type="html"> tag', () => {
    const candidate = '<artifact type="html"><div>hi</div>'
    expect(extractHtmlBlock(candidate)).toBe("<div>hi</div>")
  })

  test('is compatible with a closed <artifact type="html"> tag', () => {
    const candidate = '<artifact type="html"><div>hi</div></artifact>'
    expect(extractHtmlBlock(candidate)).toBe("<div>hi</div>")
  })
})

describe("draftFilename (M3.5)", () => {
  test("derives a .html filename for html candidates", () => {
    expect(draftFilename('# 拓扑图\n\n```html\n<div id="topo"></div>\n```')).toBe("拓扑图.html")
  })

  test("derives a .md filename for markdown candidates (backward compatible)", () => {
    expect(draftFilename("# 视频分镜脚本\n\n正文")).toBe("视频分镜脚本.md")
  })

  test("falls back to work-draft.html for html candidates without a heading", () => {
    expect(draftFilename("```html\n<div></div>\n```")).toBe("work-draft.html")
  })

  test("falls back to work-draft.md for markdown candidates without a heading", () => {
    expect(draftFilename("纯文本正文")).toBe("work-draft.md")
  })

  test("sanitizes invalid filename characters in both modes", () => {
    expect(draftFilename("# 分镜: 脚本/测试?")).toBe("分镜- 脚本-测试-.md")
    expect(draftFilename("# 拓扑: 图/测试?\n\n```html\n<div></div>\n```")).toBe("拓扑- 图-测试-.html")
  })
})

describe("wrapHtmlForDisk (M3.5 D6)", () => {
  test("injects the CSP meta and disclaimer comment", () => {
    const out = wrapHtmlForDisk("<div>hi</div>")
    expect(out).toContain("<!-- Generated by AigcForge Work mode. Review before sharing. -->")
    expect(out).toContain('http-equiv="Content-Security-Policy"')
    expect(out).toContain("connect-src 'none'")
  })

  test("injects into an existing <head> when present", () => {
    const out = wrapHtmlForDisk("<!DOCTYPE html><html><head><title>t</title></head><body><div>hi</div></body></html>")
    expect(out).toContain("<title>t</title>")
    expect(out.indexOf("Content-Security-Policy")).toBeLessThan(out.indexOf("<title>"))
    expect(out.indexOf("Content-Security-Policy")).toBeLessThan(out.indexOf("</head>"))
  })

  test("creates a full document when the html is a fragment", () => {
    const out = wrapHtmlForDisk("<div>hi</div>")
    expect(out.startsWith("<!DOCTYPE html>")).toBe(true)
    expect(out).toContain("<body>\n<div>hi</div>")
  })

  test("markdown candidates pass through unchanged", () => {
    expect(applyContentForDisk("# 分镜脚本\n\n正文")).toBe("# 分镜脚本\n\n正文")
  })

  test("html candidates are written as the extracted block wrapped with the guard", () => {
    const candidate = '# 拓扑图\n\n```html\n<div id="topo"></div>\n```'
    const out = applyContentForDisk(candidate)
    expect(out).toContain('<div id="topo"></div>')
    expect(out).not.toContain("```html")
    expect(out).toContain("Generated by AigcForge Work mode")
  })
})
