import type { Message } from "@aigcfroge/sdk/v2/client"
import { HtmlArtifactSrcdoc } from "@aigcfroge/session-ui/html-artifact-srcdoc"

/**
 * 从会话消息中提取最新含文本正文的 assistant 候选稿（D1：候选稿 = 消息正文）。
 * 跳过 tool-only 的 assistant 消息（澄清过程）；返回 null 表示尚无候选稿。
 */
export function findLatestAssistantMarkdown(
  messages: readonly Message[],
  partsByMessage: Record<string, readonly { type: string; text?: string }[] | undefined>,
): string | null {
  for (const message of messages.toReversed()) {
    if (message.role !== "assistant") continue
    const parts = partsByMessage[message.id]
    if (!parts) continue
    const text = parts
      .filter((part) => part.type === "text")
      .map((part) => part.text ?? "")
      .join("")
    if (text.trim().length > 0) return text
  }
  return null
}

/** 从候选稿首行 # 标题提取标题；无标题返回 null。draftFilename 与资产映射共用。 */
export function extractFirstHeading(markdown: string): string | null {
  const firstLine = markdown
    .split("\n")
    .map((line) => line.trim())
    .find((line) => line.startsWith("# "))
  return firstLine?.replace(/^#\s+/, "").trim() ?? null
}

/** 从候选稿首行标题派生默认文件名；无标题时用通用名。 */
export function draftFilename(content: string): string {
  const title = extractFirstHeading(content)
  const ext = detectArtifactFormat(content) === "html" ? "html" : "md"
  if (!title) return `work-draft.${ext}`
  const safe = title.replace(/[\\/:*?"<>|]/g, "-").slice(0, 80)
  return safe.endsWith(`.${ext}`) ? safe : `${safe}.${ext}`
}

/** M3.5 D1：候选稿含 ```html fenced block -> html artifact 模式；否则 markdown。 */
export function detectArtifactFormat(content: string): "html" | "markdown" {
  return /```html\n[\s\S]*?\n```/.test(content) ? "html" : "markdown"
}

/** M3.5 D7：提取首个 ```html 块；兼容 <artifact type="html"> 标签（宽松，允许未闭合）。 */
export function extractHtmlBlock(content: string): string | null {
  const fenced = content.match(/```html\n([\s\S]*?)\n```/)
  if (fenced) return fenced[1]
  const tagged = content.match(/<artifact[^>]*type=["']html["'][^>]*>([\s\S]*?)(?:<\/artifact>|$)/)
  return tagged?.[1] ?? null
}

const DISCLAIMER = "<!-- Generated by AigcForge Work mode. Review before sharing. -->"

/** 落盘 .html 时注入 CSP meta（复用 srcdoc 的 CSP_META）+ 免责注释，防离线打开外泄。 */
export function wrapHtmlForDisk(html: string): string {
  const guard = `${DISCLAIMER}\n${HtmlArtifactSrcdoc.CSP_META}`
  if (/<head[^>]*>/i.test(html)) return html.replace(/<head([^>]*)>/i, `<head$1>\n${guard}`)
  if (/<html[^>]*>/i.test(html)) return html.replace(/<html([^>]*)>/i, `<html$1>\n<head>\n${guard}\n</head>`)
  return `<!DOCTYPE html>\n<html>\n<head>\n${guard}\n</head>\n<body>\n${html}\n</body>\n</html>\n`
}

/** apply 落盘内容：html 候选稿 -> 提取块 + CSP/免责包装；markdown 原样透传。 */
export function applyContentForDisk(content: string): string {
  if (detectArtifactFormat(content) !== "html") return content
  return wrapHtmlForDisk(extractHtmlBlock(content) ?? content)
}
